### ISSUE TITLE
More switches? 

### ISSUE THREAD

**Issue by definitelynotkk** [dekuNukem/kbord#7]
Hi, really apperatiate your work, adding OLED for displaying profile is fatastic.
But 15key is just not enough when using as a numpad. 4x5 should be a proper balace between minimal and functionality.
Do you consider adding more keys in the future version?
thanks

**Comment by dekuNukem** [comment]
Hi definitelynotkk, I designed this project with more of a general keypad in mind instead of a numpad, so 15 keys were enough for me. For 20 keys, it will need more components and a microcontroller with more pins. I don't currently have plans on a new version, but since this is an open-source project, anyone can contribute and make modifications.
